package it.unipv.se2.tmtkt.model;
// Generated Jan 5, 2014 9:05:06 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookingId generated by hbm2java
 */
@Embeddable
public class BookingId  implements java.io.Serializable {


     private int eventId;
     private short seatId;

    public BookingId() {
    }

    public BookingId(int eventId, short seatId) {
       this.eventId = eventId;
       this.seatId = seatId;
    }
   


    @Column(name="EVENT_id", nullable=false)
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }


    @Column(name="SEAT_id", nullable=false)
    public short getSeatId() {
        return this.seatId;
    }
    
    public void setSeatId(short seatId) {
        this.seatId = seatId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BookingId) ) return false;
		 BookingId castOther = ( BookingId ) other; 
         
		 return (this.getEventId()==castOther.getEventId())
 && (this.getSeatId()==castOther.getSeatId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventId();
         result = 37 * result + this.getSeatId();
         return result;
   }   


}


