package it.unipv.se2.tmtkt.model;
// Generated Dec 26, 2013 12:17:49 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name="BOOKING"
    ,catalog="teatromanzoni"
)
public class Booking  implements java.io.Serializable {


     private Integer bookingId;
     private Seat seat;
     private Sale sale;
     private Event event;

    public Booking() {
    }

    public Booking(Seat seat, Sale sale, Event event) {
       this.seat = seat;
       this.sale = sale;
       this.event = event;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BOOKING_id", unique=true, nullable=false)
    public Integer getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(Integer bookingId) {
        this.bookingId = bookingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEAT_id", nullable=false)
    public Seat getSeat() {
        return this.seat;
    }
    
    public void setSeat(Seat seat) {
        this.seat = seat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SALE_id", nullable=false)
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EVENT_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }




}


