package it.unipv.se2.tmtkt.model;
// Generated Jan 2, 2014 6:25:18 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name="BOOKING"
    ,catalog="teatromanzoni"
)
public class Booking  implements java.io.Serializable {


     private BookingId id;
     private Seat seat;
     private Sale sale;
     private Event event;

    public Booking() {
    }

    public Booking(BookingId id, Seat seat, Sale sale, Event event) {
       this.id = id;
       this.seat = seat;
       this.sale = sale;
       this.event = event;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="eventId", column=@Column(name="EVENT_id", nullable=false) ), 
        @AttributeOverride(name="seatId", column=@Column(name="SEAT_id", nullable=false) ) } )
    public BookingId getId() {
        return this.id;
    }
    
    public void setId(BookingId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEAT_id", nullable=false, insertable=false, updatable=false)
    public Seat getSeat() {
        return this.seat;
    }
    
    public void setSeat(Seat seat) {
        this.seat = seat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SALE_id", nullable=false)
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EVENT_id", nullable=false, insertable=false, updatable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }




}


