package it.unipv.se2.tmtkt.model;
// Generated Dec 19, 2013 3:47:23 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CustomerCategory generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_CATEGORY"
    ,catalog="teatromanzoni"
    , uniqueConstraints = @UniqueConstraint(columnNames="DESCRIPTION") 
)
public class CustomerCategory  implements java.io.Serializable {


     private byte customerCategoryId;
     private String description;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public CustomerCategory() {
    }

	
    public CustomerCategory(byte customerCategoryId, String description) {
        this.customerCategoryId = customerCategoryId;
        this.description = description;
    }
    public CustomerCategory(byte customerCategoryId, String description, Set<Customer> customers) {
       this.customerCategoryId = customerCategoryId;
       this.description = description;
       this.customers = customers;
    }
   
     @Id 

    
    @Column(name="CUSTOMER_CATEGORY_id", unique=true, nullable=false)
    public byte getCustomerCategoryId() {
        return this.customerCategoryId;
    }
    
    public void setCustomerCategoryId(byte customerCategoryId) {
        this.customerCategoryId = customerCategoryId;
    }

    
    @Column(name="DESCRIPTION", unique=true, nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerCategory")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


