package it.unipv.se2.tmtkt.model;
// Generated Dec 19, 2013 3:47:23 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER"
    ,catalog="teatromanzoni"
    , uniqueConstraints = @UniqueConstraint(columnNames="EMAIL") 
)
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private CustomerCategory customerCategory;
     private String firstName;
     private String lastName;
     private String middleName;
     private String email;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public Customer() {
    }

	
    public Customer(CustomerCategory customerCategory, String firstName, String lastName, String email) {
        this.customerCategory = customerCategory;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
    public Customer(CustomerCategory customerCategory, String firstName, String lastName, String middleName, String email, Set<Sale> sales) {
       this.customerCategory = customerCategory;
       this.firstName = firstName;
       this.lastName = lastName;
       this.middleName = middleName;
       this.email = email;
       this.sales = sales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CUSTOMER_id", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_CATEGORY_id", nullable=false)
    public CustomerCategory getCustomerCategory() {
        return this.customerCategory;
    }
    
    public void setCustomerCategory(CustomerCategory customerCategory) {
        this.customerCategory = customerCategory;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="MIDDLE_NAME", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="EMAIL", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


