package it.unipv.se2.tmtkt.model;
// Generated Jan 15, 2014 2:28:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="EVENT"
    , uniqueConstraints = @UniqueConstraint(columnNames="DATETIME") 
)
public class Event  implements java.io.Serializable {


     private Integer eventId;
     private Play play;
     private Date datetime;
     private Set<PriceScheme> priceSchemes = new HashSet<PriceScheme>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Event() {
    }

	
    public Event(Play play, Date datetime) {
        this.play = play;
        this.datetime = datetime;
    }
    public Event(Play play, Date datetime, Set<PriceScheme> priceSchemes, Set<Booking> bookings) {
       this.play = play;
       this.datetime = datetime;
       this.priceSchemes = priceSchemes;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EVENT_id", unique=true, nullable=false)
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHOW_id", nullable=false)
    public Play getPlay() {
        return this.play;
    }
    
    public void setPlay(Play play) {
        this.play = play;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", unique=true, nullable=false, length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set<PriceScheme> getPriceSchemes() {
        return this.priceSchemes;
    }
    
    public void setPriceSchemes(Set<PriceScheme> priceSchemes) {
        this.priceSchemes = priceSchemes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


