package it.unipv.se2.tmtkt.model;
// Generated Dec 20, 2013 3:47:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="EVENT"
    ,catalog="teatromanzoni"
    , uniqueConstraints = @UniqueConstraint(columnNames="DATETIME") 
)
public class Event  implements java.io.Serializable {


     private Integer eventId;
     private Show show;
     private Date datetime;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Event() {
    }

	
    public Event(Show show, Date datetime) {
        this.show = show;
        this.datetime = datetime;
    }
    public Event(Show show, Date datetime, Set<Booking> bookings) {
       this.show = show;
       this.datetime = datetime;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EVENT_id", unique=true, nullable=false)
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHOW_id", nullable=false)
    public Show getShow() {
        return this.show;
    }
    
    public void setShow(Show show) {
        this.show = show;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", unique=true, nullable=false, length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


