package it.unipv.se2.tmtkt.model;
// Generated Dec 19, 2013 3:47:23 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PriceScheme generated by hbm2java
 */
@Entity
@Table(name="PRICE_SCHEME"
    ,catalog="teatromanzoni"
)
public class PriceScheme  implements java.io.Serializable {


     private Short priceSchemeId;
     private Season season;
     private Genre genre;
     private Sector sector;
     private Timeofday timeofday;
     private Dayofweek dayofweek;
     private long price;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public PriceScheme() {
    }

	
    public PriceScheme(Season season, Genre genre, Sector sector, Timeofday timeofday, Dayofweek dayofweek, long price) {
        this.season = season;
        this.genre = genre;
        this.sector = sector;
        this.timeofday = timeofday;
        this.dayofweek = dayofweek;
        this.price = price;
    }
    public PriceScheme(Season season, Genre genre, Sector sector, Timeofday timeofday, Dayofweek dayofweek, long price, Set<Sale> sales) {
       this.season = season;
       this.genre = genre;
       this.sector = sector;
       this.timeofday = timeofday;
       this.dayofweek = dayofweek;
       this.price = price;
       this.sales = sales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PRICE_SCHEME_id", unique=true, nullable=false)
    public Short getPriceSchemeId() {
        return this.priceSchemeId;
    }
    
    public void setPriceSchemeId(Short priceSchemeId) {
        this.priceSchemeId = priceSchemeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEASON_id", nullable=false)
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENRE_id", nullable=false)
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTOR_id", nullable=false)
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIMEOFDAY_id", nullable=false)
    public Timeofday getTimeofday() {
        return this.timeofday;
    }
    
    public void setTimeofday(Timeofday timeofday) {
        this.timeofday = timeofday;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DAYOFWEEK_id", nullable=false)
    public Dayofweek getDayofweek() {
        return this.dayofweek;
    }
    
    public void setDayofweek(Dayofweek dayofweek) {
        this.dayofweek = dayofweek;
    }

    
    @Column(name="PRICE", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="priceScheme")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


