package it.unipv.se2.tmtkt.model;
// Generated Jan 15, 2014 2:28:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PriceScheme generated by hbm2java
 */
@Entity
@Table(name="PRICE_SCHEME"
    , uniqueConstraints = @UniqueConstraint(columnNames="PRICE_SCHEME_NAME") 
)
public class PriceScheme  implements java.io.Serializable {


     private Short priceSchemeId;
     private UserCategory userCategory;
     private Play play;
     private Season season;
     private Genre genre;
     private Sector sector;
     private Timeofday timeofday;
     private Event event;
     private Dayofweek dayofweek;
     private long price;
     private String priceSchemeName;
     private Character saleType;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public PriceScheme() {
    }

	
    public PriceScheme(long price) {
        this.price = price;
    }
    public PriceScheme(UserCategory userCategory, Play play, Season season, Genre genre, Sector sector, Timeofday timeofday, Event event, Dayofweek dayofweek, long price, String priceSchemeName, Character saleType, Set<Sale> sales) {
       this.userCategory = userCategory;
       this.play = play;
       this.season = season;
       this.genre = genre;
       this.sector = sector;
       this.timeofday = timeofday;
       this.event = event;
       this.dayofweek = dayofweek;
       this.price = price;
       this.priceSchemeName = priceSchemeName;
       this.saleType = saleType;
       this.sales = sales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PRICE_SCHEME_id", unique=true, nullable=false)
    public Short getPriceSchemeId() {
        return this.priceSchemeId;
    }
    
    public void setPriceSchemeId(Short priceSchemeId) {
        this.priceSchemeId = priceSchemeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_CATEGORY_id")
    public UserCategory getUserCategory() {
        return this.userCategory;
    }
    
    public void setUserCategory(UserCategory userCategory) {
        this.userCategory = userCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHOW_id")
    public Play getPlay() {
        return this.play;
    }
    
    public void setPlay(Play play) {
        this.play = play;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEASON_id")
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENRE_id")
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTOR_id")
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIMEOFDAY_id")
    public Timeofday getTimeofday() {
        return this.timeofday;
    }
    
    public void setTimeofday(Timeofday timeofday) {
        this.timeofday = timeofday;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EVENT_id")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DAYOFWEEK_id")
    public Dayofweek getDayofweek() {
        return this.dayofweek;
    }
    
    public void setDayofweek(Dayofweek dayofweek) {
        this.dayofweek = dayofweek;
    }

    
    @Column(name="PRICE", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

    
    @Column(name="PRICE_SCHEME_NAME", unique=true, length=45)
    public String getPriceSchemeName() {
        return this.priceSchemeName;
    }
    
    public void setPriceSchemeName(String priceSchemeName) {
        this.priceSchemeName = priceSchemeName;
    }

    
    @Column(name="SALE_TYPE", length=1)
    public Character getSaleType() {
        return this.saleType;
    }
    
    public void setSaleType(Character saleType) {
        this.saleType = saleType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="priceScheme")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


