package it.unipv.se2.tmtkt.model;
// Generated Dec 19, 2013 3:47:23 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Row generated by hbm2java
 */
@Entity
@Table(name="ROW"
    ,catalog="teatromanzoni"
    , uniqueConstraints = @UniqueConstraint(columnNames="ROW_NAME") 
)
public class Row  implements java.io.Serializable {


     private int rowId;
     private String rowName;
     private Set<Seat> seats = new HashSet<Seat>(0);

    public Row() {
    }

	
    public Row(int rowId, String rowName) {
        this.rowId = rowId;
        this.rowName = rowName;
    }
    public Row(int rowId, String rowName, Set<Seat> seats) {
       this.rowId = rowId;
       this.rowName = rowName;
       this.seats = seats;
    }
   
     @Id 

    
    @Column(name="ROW_id", unique=true, nullable=false)
    public int getRowId() {
        return this.rowId;
    }
    
    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    
    @Column(name="ROW_NAME", unique=true, nullable=false, length=45)
    public String getRowName() {
        return this.rowName;
    }
    
    public void setRowName(String rowName) {
        this.rowName = rowName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="row")
    public Set<Seat> getSeats() {
        return this.seats;
    }
    
    public void setSeats(Set<Seat> seats) {
        this.seats = seats;
    }




}


