package it.unipv.se2.tmtkt.model;
// Generated Jan 15, 2014 2:28:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name="SALE")
public class Sale  implements java.io.Serializable {


     private Integer saleId;
     private User user;
     private Payment payment;
     private PriceScheme priceScheme;
     private char saleType;
     private Set<Booking> bookings = new HashSet<Booking>(0);
     private Ticket ticket;
     private Subscription subscription;

    public Sale() {
    }

	
    public Sale(User user, Payment payment, PriceScheme priceScheme, char saleType) {
        this.user = user;
        this.payment = payment;
        this.priceScheme = priceScheme;
        this.saleType = saleType;
    }
    public Sale(User user, Payment payment, PriceScheme priceScheme, char saleType, Set<Booking> bookings, Ticket ticket, Subscription subscription) {
       this.user = user;
       this.payment = payment;
       this.priceScheme = priceScheme;
       this.saleType = saleType;
       this.bookings = bookings;
       this.ticket = ticket;
       this.subscription = subscription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SALE_id", unique=true, nullable=false)
    public Integer getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_EMAIL", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAYMENT_id", nullable=false)
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRICE_SCHEME_id", nullable=false)
    public PriceScheme getPriceScheme() {
        return this.priceScheme;
    }
    
    public void setPriceScheme(PriceScheme priceScheme) {
        this.priceScheme = priceScheme;
    }

    
    @Column(name="SALE_TYPE", nullable=false, length=1)
    public char getSaleType() {
        return this.saleType;
    }
    
    public void setSaleType(char saleType) {
        this.saleType = saleType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sale")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="sale")
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="sale")
    public Subscription getSubscription() {
        return this.subscription;
    }
    
    public void setSubscription(Subscription subscription) {
        this.subscription = subscription;
    }




}


