package it.unipv.se2.tmtkt.model;
// Generated Jan 2, 2014 6:25:18 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Show generated by hbm2java
 */
@Entity
@Table(name="SHOW"
    ,catalog="teatromanzoni"
)
public class Show  implements java.io.Serializable {


     private Short showId;
     private Genre genre;
     private String title;
     private String authorName;
     private String directorName;
     private String description;
     private Date firstEventDate;
     private Date lastEventDate;
     private Set<Event> events = new HashSet<Event>(0);

    public Show() {
    }

	
    public Show(Genre genre, String title) {
        this.genre = genre;
        this.title = title;
    }
    public Show(Genre genre, String title, String authorName, String directorName, String description, Date firstEventDate, Date lastEventDate, Set<Event> events) {
       this.genre = genre;
       this.title = title;
       this.authorName = authorName;
       this.directorName = directorName;
       this.description = description;
       this.firstEventDate = firstEventDate;
       this.lastEventDate = lastEventDate;
       this.events = events;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SHOW_id", unique=true, nullable=false)
    public Short getShowId() {
        return this.showId;
    }
    
    public void setShowId(Short showId) {
        this.showId = showId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENRE_id", nullable=false)
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }

    
    @Column(name="TITLE", nullable=false, length=80)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="AUTHOR_NAME", length=80)
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    
    @Column(name="DIRECTOR_NAME", length=80)
    public String getDirectorName() {
        return this.directorName;
    }
    
    public void setDirectorName(String directorName) {
        this.directorName = directorName;
    }

    
    @Column(name="DESCRIPTION", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FIRST_EVENT_DATE", length=10)
    public Date getFirstEventDate() {
        return this.firstEventDate;
    }
    
    public void setFirstEventDate(Date firstEventDate) {
        this.firstEventDate = firstEventDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_EVENT_DATE", length=10)
    public Date getLastEventDate() {
        return this.lastEventDate;
    }
    
    public void setLastEventDate(Date lastEventDate) {
        this.lastEventDate = lastEventDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="show")
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }




}


