package it.unipv.se2.tmtkt.model;
// Generated Dec 26, 2013 12:17:49 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubscriptionType generated by hbm2java
 */
@Entity
@Table(name="SUBSCRIPTION_TYPE"
    ,catalog="teatromanzoni"
)
public class SubscriptionType  implements java.io.Serializable {


     private short subscriptionTypeId;
     private String name;
     private Set<Subscription> subscriptions = new HashSet<Subscription>(0);

    public SubscriptionType() {
    }

	
    public SubscriptionType(short subscriptionTypeId, String name) {
        this.subscriptionTypeId = subscriptionTypeId;
        this.name = name;
    }
    public SubscriptionType(short subscriptionTypeId, String name, Set<Subscription> subscriptions) {
       this.subscriptionTypeId = subscriptionTypeId;
       this.name = name;
       this.subscriptions = subscriptions;
    }
   
     @Id 

    
    @Column(name="SUBSCRIPTION_TYPE_id", unique=true, nullable=false)
    public short getSubscriptionTypeId() {
        return this.subscriptionTypeId;
    }
    
    public void setSubscriptionTypeId(short subscriptionTypeId) {
        this.subscriptionTypeId = subscriptionTypeId;
    }

    
    @Column(name="NAME", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subscriptionType")
    public Set<Subscription> getSubscriptions() {
        return this.subscriptions;
    }
    
    public void setSubscriptions(Set<Subscription> subscriptions) {
        this.subscriptions = subscriptions;
    }




}


