package it.unipv.se2.tmtkt.model;
// Generated Dec 19, 2013 3:47:23 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubscriptionId generated by hbm2java
 */
@Embeddable
public class SubscriptionId  implements java.io.Serializable {


     private int subscriptionId;
     private int saleId;

    public SubscriptionId() {
    }

    public SubscriptionId(int subscriptionId, int saleId) {
       this.subscriptionId = subscriptionId;
       this.saleId = saleId;
    }
   


    @Column(name="SUBSCRIPTION_id", nullable=false)
    public int getSubscriptionId() {
        return this.subscriptionId;
    }
    
    public void setSubscriptionId(int subscriptionId) {
        this.subscriptionId = subscriptionId;
    }


    @Column(name="SALE_id", nullable=false)
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubscriptionId) ) return false;
		 SubscriptionId castOther = ( SubscriptionId ) other; 
         
		 return (this.getSubscriptionId()==castOther.getSubscriptionId())
 && (this.getSaleId()==castOther.getSaleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSubscriptionId();
         result = 37 * result + this.getSaleId();
         return result;
   }   


}


