package it.unipv.se2.tmtkt.model;
// Generated Jan 15, 2014 2:28:27 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name="SUBSCRIPTION"
    , uniqueConstraints = @UniqueConstraint(columnNames="SUBSCRIPTION_id") 
)
public class Subscription  implements java.io.Serializable {


     private int saleId;
     private Seat seat;
     private Genre genre;
     private Sale sale;
     private SubscriptionType subscriptionType;
     private int subscriptionId;
     private Short prepaidTickets;

    public Subscription() {
    }

	
    public Subscription(Genre genre, Sale sale, SubscriptionType subscriptionType, int subscriptionId) {
        this.genre = genre;
        this.sale = sale;
        this.subscriptionType = subscriptionType;
        this.subscriptionId = subscriptionId;
    }
    public Subscription(Seat seat, Genre genre, Sale sale, SubscriptionType subscriptionType, int subscriptionId, Short prepaidTickets) {
       this.seat = seat;
       this.genre = genre;
       this.sale = sale;
       this.subscriptionType = subscriptionType;
       this.subscriptionId = subscriptionId;
       this.prepaidTickets = prepaidTickets;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="sale"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="SALE_id", unique=true, nullable=false)
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEAT_id")
    public Seat getSeat() {
        return this.seat;
    }
    
    public void setSeat(Seat seat) {
        this.seat = seat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENRE_id", nullable=false)
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUBSCRIPTION_TYPE_id", nullable=false)
    public SubscriptionType getSubscriptionType() {
        return this.subscriptionType;
    }
    
    public void setSubscriptionType(SubscriptionType subscriptionType) {
        this.subscriptionType = subscriptionType;
    }

    
    @Column(name="SUBSCRIPTION_id", unique=true, nullable=false)
    public int getSubscriptionId() {
        return this.subscriptionId;
    }
    
    public void setSubscriptionId(int subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    
    @Column(name="PREPAID_TICKETS")
    public Short getPrepaidTickets() {
        return this.prepaidTickets;
    }
    
    public void setPrepaidTickets(Short prepaidTickets) {
        this.prepaidTickets = prepaidTickets;
    }




}


