package it.unipv.se2.tmtkt.model;
// Generated Jan 4, 2014 12:15:21 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="TICKET"
    ,catalog="teatromanzoni"
    , uniqueConstraints = @UniqueConstraint(columnNames="TICKET_id") 
)
public class Ticket  implements java.io.Serializable {


     private int saleId;
     private Sale sale;
     private int ticketId;

    public Ticket() {
    }

    public Ticket(Sale sale, int ticketId) {
       this.sale = sale;
       this.ticketId = ticketId;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="sale"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="SALE_id", unique=true, nullable=false)
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }

    
    @Column(name="TICKET_id", unique=true, nullable=false)
    public int getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }




}


