package it.unipv.se2.tmtkt.model;
// Generated Dec 20, 2013 3:47:27 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="TICKET"
    ,catalog="teatromanzoni"
)
public class Ticket  implements java.io.Serializable {


     private Integer ticketId;
     private Sale sale;

    public Ticket() {
    }

    public Ticket(Sale sale) {
       this.sale = sale;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TICKET_id", unique=true, nullable=false)
    public Integer getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SALE_id", nullable=false)
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }




}


