package it.unipv.se2.tmtkt.model;
// Generated Dec 19, 2013 10:08:59 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timeofday generated by hbm2java
 */
@Entity
@Table(name="TIMEOFDAY"
    ,catalog="teatromanzoni"
)
public class Timeofday  implements java.io.Serializable {


     private Byte timeofdayId;
     private Date startTime;
     private String endTime;
     private Set<PriceScheme> priceSchemes = new HashSet<PriceScheme>(0);

    public Timeofday() {
    }

    public Timeofday(Date startTime, String endTime, Set<PriceScheme> priceSchemes) {
       this.startTime = startTime;
       this.endTime = endTime;
       this.priceSchemes = priceSchemes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TIMEOFDAY_id", unique=true, nullable=false)
    public Byte getTimeofdayId() {
        return this.timeofdayId;
    }
    
    public void setTimeofdayId(Byte timeofdayId) {
        this.timeofdayId = timeofdayId;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="START_TIME", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="END_TIME", length=45)
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="timeofday")
    public Set<PriceScheme> getPriceSchemes() {
        return this.priceSchemes;
    }
    
    public void setPriceSchemes(Set<PriceScheme> priceSchemes) {
        this.priceSchemes = priceSchemes;
    }




}


