package it.unipv.se2.tmtkt.model;
// Generated Dec 20, 2013 3:47:27 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="USER"
    ,catalog="teatromanzoni"
    , uniqueConstraints = @UniqueConstraint(columnNames="EMAIL") 
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private UserCategory userCategory;
     private String firstName;
     private String lastName;
     private String middleName;
     private String email;
     private String password;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public User() {
    }

	
    public User(UserCategory userCategory, String firstName, String lastName, String email) {
        this.userCategory = userCategory;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
    public User(UserCategory userCategory, String firstName, String lastName, String middleName, String email, String password, Set<Sale> sales) {
       this.userCategory = userCategory;
       this.firstName = firstName;
       this.lastName = lastName;
       this.middleName = middleName;
       this.email = email;
       this.password = password;
       this.sales = sales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USER_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_CATEGORY_USER_CATEGORY_id", nullable=false)
    public UserCategory getUserCategory() {
        return this.userCategory;
    }
    
    public void setUserCategory(UserCategory userCategory) {
        this.userCategory = userCategory;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="MIDDLE_NAME", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="EMAIL", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PASSWORD", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }

    public String toString() {
    	return this.getFirstName() + ' ' + this.getLastName();
    }


}


